package com.model;

/**
 * TToupiao generated by MyEclipse Persistence Tools
 */

public class TToupiao implements java.io.Serializable
{

	// Fields

	private Integer toupiaoId;

	private String toupiaoName;

	private String toupiaoDate;

	// Constructors

	/** default constructor */
	public TToupiao()
	{
	}

	/** full constructor */
	public TToupiao(String toupiaoName, Integer toupiaoDate)
	{
	}

	// Property accessors

	public Integer getToupiaoId()
	{
		return this.toupiaoId;
	}

	public void setToupiaoId(Integer toupiaoId)
	{
		this.toupiaoId = toupiaoId;
	}

	public String getToupiaoName()
	{
		return this.toupiaoName;
	}

	public void setToupiaoName(String toupiaoName)
	{
		this.toupiaoName = toupiaoName;
	}

	public String getToupiaoDate()
	{
		return toupiaoDate;
	}

	public void setToupiaoDate(String toupiaoDate)
	{
		this.toupiaoDate = toupiaoDate;
	}


}