package com.model;

/**
 * TYuding generated by MyEclipse Persistence Tools
 */

public class TYuding implements java.io.Serializable
{

	// Fields

	private Integer yudingId;

	private Integer userId;

	private Integer checiId;

	private Integer yudingShumu;

	private String yudingJine;

	private String zhifufangshi;
	
	private String yudingShijian;
	
	private int yudingZhuantai;//0未受理。1受理。2删除

	// Constructors

	/** default constructor */
	public TYuding()
	{
	}

	/** full constructor */
	public TYuding(Integer userId, Integer checiId, Integer yudingShumu,
			String yudingJine, int yudingZhuantai)
	{
		this.userId = userId;
		this.checiId = checiId;
		this.yudingShumu = yudingShumu;
		this.yudingJine = yudingJine;
		this.yudingZhuantai = yudingZhuantai;
	}

	// Property accessors

	public Integer getYudingId()
	{
		return this.yudingId;
	}

	public void setYudingId(Integer yudingId)
	{
		this.yudingId = yudingId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getZhifufangshi()
	{
		return zhifufangshi;
	}

	public void setZhifufangshi(String zhifufangshi)
	{
		this.zhifufangshi = zhifufangshi;
	}

	public Integer getCheciId()
	{
		return this.checiId;
	}

	public void setCheciId(Integer checiId)
	{
		this.checiId = checiId;
	}

	public Integer getYudingShumu()
	{
		return this.yudingShumu;
	}

	public void setYudingShumu(Integer yudingShumu)
	{
		this.yudingShumu = yudingShumu;
	}

	public String getYudingJine()
	{
		return this.yudingJine;
	}

	public void setYudingJine(String yudingJine)
	{
		this.yudingJine = yudingJine;
	}

	public int getYudingZhuantai()
	{
		return yudingZhuantai;
	}

	public void setYudingZhuantai(int yudingZhuantai)
	{
		this.yudingZhuantai = yudingZhuantai;
	}

	public String getYudingShijian()
	{
		return yudingShijian;
	}

	public void setYudingShijian(String yudingShijian)
	{
		this.yudingShijian = yudingShijian;
	}


}